Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
The module project_websocket.project_websocket was not found.

Error: 
Unable to load celery application.
The module project_websocket.project_websocket was not found.

Error: 
Unable to load celery application.
The module project_websocket.project_websocket was not found.

Error: 
Unable to load celery application.
The module project_websocket.project_websocket was not found.

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

Error: 
Unable to load celery application.
Module 'project_websocket' has no attribute 'celery'

[2022-02-03 15:41:40,956: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named 'django-db'",)
Traceback (most recent call last):
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/worker/worker.py", line 208, in start
    self.blueprint.start(self)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 140, in on_start
    self.emit_banner()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 155, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 218, in startup_info
    results=self.app.backend.as_uri(),
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/base.py", line 1193, in backend
    return self._get_backend()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/base.py", line 910, in _get_backend
    self.loader)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/backends.py", line 74, in by_url
    return by_name(backend, loader), url
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/backends.py", line 54, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-db'
[2022-02-03 15:41:43,066: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named 'django-db'",)
Traceback (most recent call last):
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/worker/worker.py", line 208, in start
    self.blueprint.start(self)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 140, in on_start
    self.emit_banner()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 155, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 218, in startup_info
    results=self.app.backend.as_uri(),
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/base.py", line 1193, in backend
    return self._get_backend()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/base.py", line 910, in _get_backend
    self.loader)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/backends.py", line 74, in by_url
    return by_name(backend, loader), url
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/backends.py", line 54, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-db'
[2022-02-03 15:41:47,370: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named 'django-db'",)
Traceback (most recent call last):
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/worker/worker.py", line 208, in start
    self.blueprint.start(self)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 140, in on_start
    self.emit_banner()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 155, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 218, in startup_info
    results=self.app.backend.as_uri(),
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/base.py", line 1193, in backend
    return self._get_backend()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/base.py", line 910, in _get_backend
    self.loader)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/backends.py", line 74, in by_url
    return by_name(backend, loader), url
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/backends.py", line 54, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-db'
[2022-02-03 15:41:51,907: CRITICAL/MainProcess] Unrecoverable error: ModuleNotFoundError("No module named 'django-db'",)
Traceback (most recent call last):
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/worker/worker.py", line 208, in start
    self.blueprint.start(self)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 140, in on_start
    self.emit_banner()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 155, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/apps/worker.py", line 218, in startup_info
    results=self.app.backend.as_uri(),
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/base.py", line 1193, in backend
    return self._get_backend()
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/base.py", line 910, in _get_backend
    self.loader)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/backends.py", line 74, in by_url
    return by_name(backend, loader), url
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/celery/app/backends.py", line 54, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/home/luis/Documentos/project/project_websocket/env_project_websocket/lib/python3.6/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django-db'
